exports.data = [
  {
    riduculously_long_field_name_riduculously_long_field_name: "1",
    mechanical_designation: "T",
    equipment_type_code: "T104",
    rule_83_car_kind: "T",
    owner: "UTCX",
    maintenance_part: "UTCX",
    mark_owner_category: "B",
    last_update_date: "08/27/2017",
    equipment_add_date: "04/07/2007",
    status_change_reason: "M",
    status_change_date: "08/11/2009",
    extended_service: "E",
    equipment_identification: 1234567,
    rate_indicator: 2,
    first_movement_date: "02/17/2007",
    registration_reason: "N",

    gross_rail_load_weight: 264000,
    tare_weight: 60300,
    load_limit: 202700,
    weighing_status: "A",
    weighing_date: "04/21/2008",
    gallonage_capacity: 16540,

    plate_code: "B",
    outside_length: "42'3\"",
    outside_extreme_width: "10'8\"",
    outside_extreme_height: "15'1\"",
    outside_height_extr_width: "3'6\"",
    truck_center_length: "27'4\"",
  },
  {
    status_code: "B",
    mechanical_designation: "T",
    equipment_type_code: "T104",
    rule_83_car_kind: "T",
    owner: "UTCX",
    maintenance_part: "UTCX",
    mark_owner_category: "B",
    last_update_date: "08/27/2017",
    equipment_add_date: "04/07/2007",
    status_change_reason: "M",
    status_change_date: "08/11/2009",
    extended_service: "E",
    equipment_identification: 2234567,
    rate_indicator: 2,
    first_movement_date: "02/17/2007",
    registration_reason: "N",

    gross_rail_load_weight: 264000,
    tare_weight: 60300,
    load_limit: 202700,
    weighing_status: "A",
    weighing_date: "04/21/2008",
    gallonage_capacity: 16540,

    plate_code: "B",
    outside_length: "42'3\"",
    outside_extreme_width: "10'8\"",
    outside_extreme_height: "15'1\"",
    outside_height_extr_width: "3'6\"",
    truck_center_length: "27'4\"",
  },
  {
    status_code: "C",
    mechanical_designation: "T",
    equipment_type_code: "T104",
    rule_83_car_kind: "T",
    owner: "UTCX",
    maintenance_part: "UTCX",
    mark_owner_category: "B",
    last_update_date: "08/27/2017",
    equipment_add_date: "04/07/2007",
    status_change_reason: "M",
    status_change_date: "08/11/2009",
    extended_service: "E",
    equipment_identification: 3234567,
    rate_indicator: 2,
    first_movement_date: "02/17/2007",
    registration_reason: "N",

    gross_rail_load_weight: 264000,
    tare_weight: 60300,
    load_limit: 202700,
    weighing_status: "A",
    weighing_date: "04/21/2008",
    gallonage_capacity: 16540,

    plate_code: "B",
    outside_length: "42'3\"",
    outside_extreme_width: "10'8\"",
    outside_extreme_height: "15'1\"",
    outside_height_extr_width: "3'6\"",
    truck_center_length: "27'4\"",
  },
]

exports.generalFields = [
  "status_code",
  "mechanical_designation",
  "equipment_type_code",
  "rule_83_car_kind",
  "owner",
  "maintenance_part",
  "mark_owner_category",
  "last_update_date",
  "equipment_add_date",
  "status_change_reason",
  "status_change_date",
  "extended_service",
  "equipment_identification",
  "rate_indicator",
  "first_movement_date",
  "registration_reason",
];

exports.weightFields = [
  "gross_rail_load_weight",
  "tare_weight",
  "load_limit",
  "weighing_status",
  "weighing_date",
  "gallonage_capacity",
];

exports.dimensionFields = [
  "plate_code",
  "outside_length",
  "outside_extreme_width",
  "outside_extreme_height",
  "outside_height_extr_width",
  "truck_center_length",
];